import Link from "next/link";
import { ArrowUpRight, Bell, BookOpen, CalendarDays, ChevronRight, CircleAlert, CircleCheck, GraduationCap, MessageCircle } from "lucide-react";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { StatusPill } from "@/components/ui/StatusPill";
import { ResourceRow } from "@/components/student/ResourceRow";
import { ScheduleRow } from "@/components/student/ScheduleRow";
import { recentMaterials, studentInvoices, studentProfile, upcomingClasses } from "@/services/studentService";

export function DashboardOverview() {
  return (
    <>
      <section className="welcome-band"><div className="welcome-copy"><p className="section-eyebrow">Tuesday, 25 August 2026</p><h1>Good morning, Sahan.</h1><p className="welcome-description">Keep your momentum going. You have one class and two new resources waiting today.</p><div className="welcome-tags"><span><GraduationCap size={16} /> {studentProfile.exam}</span><span><BookOpen size={16} /> {studentProfile.stream}</span><span>{studentProfile.medium}</span></div></div><div className="focus-meter" aria-label="Your weekly focus is 78 percent"><div className="focus-meter-top"><span>Weekly focus</span><strong>78%</strong></div><div className="meter-track"><span style={{ width: "78%" }} /></div><p>Up 12% from last week</p></div></section>

      <section className="metric-grid" aria-label="Learning summary"><article className="metric-card metric-card-coral"><div className="metric-icon"><CalendarDays size={19} /></div><div><p>Classes this week</p><strong>06</strong><span>2 completed</span></div><ArrowUpRight className="metric-arrow" size={17} /></article><article className="metric-card metric-card-green"><div className="metric-icon"><CircleCheck size={19} /></div><div><p>Attendance rate</p><strong>92%</strong><span>Excellent consistency</span></div><ArrowUpRight className="metric-arrow" size={17} /></article><article className="metric-card metric-card-yellow"><div className="metric-icon"><BookOpen size={19} /></div><div><p>New materials</p><strong>03</strong><span>Since your last visit</span></div><ArrowUpRight className="metric-arrow" size={17} /></article></section>

      <div className="dashboard-grid"><section className="section-block schedule-block"><SectionHeading eyebrow="Your week" title="Upcoming classes" action={<Link className="text-button" href="/schedule">Full schedule <ChevronRight size={16} /></Link>} /><div className="schedule-list"><ScheduleRow item={upcomingClasses[0]} featured /><ScheduleRow item={upcomingClasses[1]} /><ScheduleRow item={upcomingClasses[2]} /></div></section><aside className="section-block announcement-block"><SectionHeading eyebrow="From your institute" title="Notice board" action={<button className="icon-button subtle" type="button" title="View all announcements" aria-label="View all announcements"><ArrowUpRight size={17} /></button>} /><div className="notice-item notice-important"><div className="notice-mark"><CircleAlert size={17} /></div><div><span className="notice-label">Important</span><h3>Term test paper 02</h3><p>Submit your answer script by Friday, 29 August.</p><span className="notice-time">Posted 1 hour ago</span></div></div><div className="notice-item notice-reminder"><div className="notice-mark notice-mark-neutral"><Bell size={17} /></div><div><span className="notice-label">Reminder</span><h3>August fee deadline</h3><p>Your mathematics fee is due in 5 days.</p><span className="notice-time">Posted yesterday</span></div></div><div className="notice-item notice-update"><div className="notice-mark"><CircleCheck size={17} /></div><div><span className="notice-label">Update</span><h3>New study materials added</h3><p>3 new PDFs uploaded for Combined Mathematics.</p><span className="notice-time">Posted 3 hours ago</span></div></div><Link className="outline-button notice-button" href="/messages">Open messages <MessageCircle size={16} /></Link></aside></div>

      <div className="dashboard-grid bottom-grid"><section className="section-block"><SectionHeading eyebrow="Keep learning" title="Recent materials" action={<Link className="text-button" href="/materials">View library <ChevronRight size={16} /></Link>} /><div className="resource-list">{recentMaterials.slice(0, 2).map((resource) => <ResourceRow key={resource.title} resource={resource} />)}</div></section><section className="section-block fees-block"><SectionHeading eyebrow="Account" title="Fee overview" action={<Link className="text-button" href="/fees">View fees <ChevronRight size={16} /></Link>} /><div className="fee-overview"><div><span>Outstanding</span><strong>{studentInvoices[0].amount}</strong></div><StatusPill tone="warning">{studentInvoices[0].status}</StatusPill></div><div className="fee-progress"><span style={{ width: "62%" }} /></div><p className="fee-caption">1 of 2 August invoices paid</p></section></div>
    </>
  );
}
